// Mocks generated by Mockito — regenerar con: dart run build_runner build
// ignore_for_file: type=lint

import 'package:dartz/dartz.dart';
import 'package:mockito/mockito.dart';
import 'package:shinra_city/core/errors/failures.dart';
import 'package:shinra_city/domain/entities/user_entity.dart';
import 'package:shinra_city/domain/repositories/auth_repository.dart';

class MockAuthRepository extends Mock implements AuthRepository {
  @override
  Stream<UserEntity?> get authStateChanges =>
      super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: const Stream<UserEntity?>.empty(),
        returnValueForMissingStub: const Stream<UserEntity?>.empty(),
      ) as Stream<UserEntity?>;

  @override
  Future<Either<Failure, UserEntity>> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      super.noSuchMethod(
        Invocation.method(#signInWithEmail, [], {
          #email: email,
          #password: password,
        }),
        returnValue: Future.value(
          const Left<Failure, UserEntity>(
            ServerFailure(message: 'mock'),
          ),
        ),
        returnValueForMissingStub: Future.value(
          const Left<Failure, UserEntity>(
            ServerFailure(message: 'mock'),
          ),
        ),
      ) as Future<Either<Failure, UserEntity>>;

  @override
  Future<Either<Failure, UserEntity>> signUpWithEmail({
    required String? email,
    required String? password,
    required String? displayName,
    String accountType = 'user',
  }) =>
      super.noSuchMethod(
        Invocation.method(#signUpWithEmail, [], {
          #email: email,
          #password: password,
          #displayName: displayName,
          #accountType: accountType,
        }),
        returnValue: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
        returnValueForMissingStub: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
      ) as Future<Either<Failure, UserEntity>>;

  @override
  Future<Either<Failure, UserEntity>> signInWithGoogle() =>
      super.noSuchMethod(
        Invocation.method(#signInWithGoogle, []),
        returnValue: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
        returnValueForMissingStub: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
      ) as Future<Either<Failure, UserEntity>>;

  @override
  Future<Either<Failure, UserEntity>> signInWithApple() =>
      super.noSuchMethod(
        Invocation.method(#signInWithApple, []),
        returnValue: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
        returnValueForMissingStub: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
      ) as Future<Either<Failure, UserEntity>>;

  @override
  Future<Either<Failure, UserEntity>> signInWithFacebook() =>
      super.noSuchMethod(
        Invocation.method(#signInWithFacebook, []),
        returnValue: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
        returnValueForMissingStub: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
      ) as Future<Either<Failure, UserEntity>>;

  @override
  Future<Either<Failure, void>> signOut() =>
      super.noSuchMethod(
        Invocation.method(#signOut, []),
        returnValue: Future.value(const Right<Failure, void>(null)),
        returnValueForMissingStub:
            Future.value(const Right<Failure, void>(null)),
      ) as Future<Either<Failure, void>>;

  @override
  Future<Either<Failure, void>> sendPasswordResetEmail(String? email) =>
      super.noSuchMethod(
        Invocation.method(#sendPasswordResetEmail, [email]),
        returnValue: Future.value(const Right<Failure, void>(null)),
        returnValueForMissingStub:
            Future.value(const Right<Failure, void>(null)),
      ) as Future<Either<Failure, void>>;

  @override
  Future<Either<Failure, void>> sendEmailVerification() =>
      super.noSuchMethod(
        Invocation.method(#sendEmailVerification, []),
        returnValue: Future.value(const Right<Failure, void>(null)),
        returnValueForMissingStub:
            Future.value(const Right<Failure, void>(null)),
      ) as Future<Either<Failure, void>>;

  @override
  Future<Either<Failure, UserEntity>> getCurrentUser() =>
      super.noSuchMethod(
        Invocation.method(#getCurrentUser, []),
        returnValue: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
        returnValueForMissingStub: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
      ) as Future<Either<Failure, UserEntity>>;

  @override
  Future<Either<Failure, UserEntity>> updateProfile({
    String? displayName,
    String? photoUrl,
    String? phoneNumber,
  }) =>
      super.noSuchMethod(
        Invocation.method(#updateProfile, [], {
          #displayName: displayName,
          #photoUrl: photoUrl,
          #phoneNumber: phoneNumber,
        }),
        returnValue: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
        returnValueForMissingStub: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
      ) as Future<Either<Failure, UserEntity>>;

  @override
  Future<Either<Failure, void>> updateFcmToken(String? token) =>
      super.noSuchMethod(
        Invocation.method(#updateFcmToken, [token]),
        returnValue: Future.value(const Right<Failure, void>(null)),
        returnValueForMissingStub:
            Future.value(const Right<Failure, void>(null)),
      ) as Future<Either<Failure, void>>;

  @override
  Future<Either<Failure, UserEntity>> updateSettings({
    bool? notificationsEnabled,
    bool? locationEnabled,
  }) =>
      super.noSuchMethod(
        Invocation.method(#updateSettings, [], {
          #notificationsEnabled: notificationsEnabled,
          #locationEnabled: locationEnabled,
        }),
        returnValue: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
        returnValueForMissingStub: Future.value(
          const Left<Failure, UserEntity>(ServerFailure(message: 'mock')),
        ),
      ) as Future<Either<Failure, UserEntity>>;

  @override
  Future<Either<Failure, void>> deleteAccount() =>
      super.noSuchMethod(
        Invocation.method(#deleteAccount, []),
        returnValue: Future.value(const Right<Failure, void>(null)),
        returnValueForMissingStub:
            Future.value(const Right<Failure, void>(null)),
      ) as Future<Either<Failure, void>>;

  @override
  Future<Either<Failure, UserEntity?>> getUserByEmail(String? email) =>
      super.noSuchMethod(
        Invocation.method(#getUserByEmail, [email]),
        returnValue: Future.value(const Right<Failure, UserEntity?>(null)),
      );

  @override
  Future<Either<Failure, UserEntity?>> getUserById(String? userId) =>
      super.noSuchMethod(
        Invocation.method(#getUserById, [userId]),
        returnValue: Future.value(const Right<Failure, UserEntity?>(null)),
      );
}
