// Generated by FlutterFire CLI — replace values with your project config.
// Run: flutterfire configure
// See: https://firebase.flutter.dev/docs/cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your Firebase project values from google-services.json

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATq2H5j-MZzq13VY-0C2-Q2C2SZGbfDaI',
    appId: '1:870088430256:android:ec962ae9683035a1bf6175',
    messagingSenderId: '870088430256',
    projectId: 'shinra-city',
    storageBucket: 'shinra-city.firebasestorage.app',
  );
  // TODO: Replace with your Firebase project values from GoogleService-Info.plist

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl5sEUi3qZMgyqslcxtifREf246tnqxpU',
    appId: '1:870088430256:ios:6a713308cfcd90dbbf6175',
    messagingSenderId: '870088430256',
    projectId: 'shinra-city',
    storageBucket: 'shinra-city.firebasestorage.app',
    iosClientId: '870088430256-djjcmbkv6eguo2sljch4p9tkvtvc6nj4.apps.googleusercontent.com',
    iosBundleId: 'com.shinracity.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:web:YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'shinra-city',
    storageBucket: 'shinra-city.appspot.com',
    authDomain: 'shinra-city.firebaseapp.com',
  );
}
